### ISSUE TITLE
Unable to scrape prometheus rsocket proxy /metrics/connected endpoint when multiple apps send to proxy server

### ISSUE THREAD

**Issue by Delmonte3161** [cloudfoundry/metric-store-release#127]
### Is this an Issue/Bug or a Feature Request?
[x] Issue or Bug
[ ] Feature Request

### What is this issue about? Or why do you want this feature?
We use the [prometheus rsocket proxy](https://github.com/micrometer-metrics/prometheus-rsocket-proxy) to collect all of our app metrics, across many microservices, and expose it to prometheus.  We would like to be able to ingest that endpoint into the metrics store but when more than one app is sending metrics to the prometheus rsocket proxy, the /metrics/connected no longer is properly scraped by the metrics registrar.  If the proxy is only receiving a single app's metrics, it works fine.  Prometheus itself can ingest the proxy's endpoint just fine however.

This feature is important as it means all of our microservices only have to open an rsocket connection to the proxy server instead of configuring each to be scraped into the metrics store.  Then the only endpoint the metrics store needs to scrape if the proxy's /metrics/connected endpoint and need not know about all the other applications.

##### What version of Metric Store are you using?
Unsure, as this is managed by our platform team but I can update when I know.  I assume it is the latest release as we stay current.  I will ask our platform team to comment on this issue.

##### Please provide output that helps describe the issue:
There does not appear to be any significant output with an error indicating why it cannot be ingested.  

##### Is there anything unique or special about your setup?
Not that I am aware of.  I will ask our platform team to comment on this issue.

**Comment by thepeterstone** [comment]
Howdy @Delmonte3161, thanks for the report!

I think you'll want to file this against [metric-registrar](https://github.com/pivotal-cf/metric-registrar-release/issues) directly since it appears to be an issue with scraping / registration. I'll close this for the time being - feel free to reopen if needed.

**Comment by xyloman** [comment]
@thepeterstone I was working with @Delmonte3161 and we were not able to actually deduce that it was a scraping registration issue because we thought the metrics were scraped but were not queryable by metric store.  We were not able to figure out where in the logs to find an exception that would let us know why the metrics could not be queried.
